// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQQDH7IxYTlnojZ0B3UtazYH-N_ENlsAs',
    appId: '1:1007046806650:web:01dc2c0f4c537ea2627fc3',
    messagingSenderId: '1007046806650',
    projectId: 'meetia-a4b70',
    authDomain: 'meetia-a4b70.firebaseapp.com',
    storageBucket: 'meetia-a4b70.appspot.com',
    measurementId: 'G-V9B007XZZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGpoiZjb0X1sZVgZ25AVOUO_Wx-ZhDi9M',
    appId: '1:1007046806650:android:e8fecab5636b5e8e627fc3',
    messagingSenderId: '1007046806650',
    projectId: 'meetia-a4b70',
    storageBucket: 'meetia-a4b70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHFx8O4BuBj1xKj_PDLIZAkBQdhaLxkQE',
    appId: '1:1007046806650:ios:f61f73b8d642454f627fc3',
    messagingSenderId: '1007046806650',
    projectId: 'meetia-a4b70',
    storageBucket: 'meetia-a4b70.appspot.com',
    iosClientId: '1007046806650-62i50n7h2vrofl2f82pshq524g5ilhcf.apps.googleusercontent.com',
    iosBundleId: 'com.meetia.app',
  );
}
